version: '3.8'

services:
  bookstoredatabase:
    container_name: bookstoredatabase
    image: mysql:8.0
    environment:
      MYSQL_DATABASE: bookstore
      MYSQL_USER: erva
      MYSQL_PASSWORD: password
      MYSQL_ROOT_PASSWORD: password
    ports:
      - '3308:3306'
    healthcheck:
      test: mysql bookstore --user=erva --password='password' --silent --execute "SELECT 1;"
      interval: 15s
      timeout: 3s
      retries: 20
  bookstorebackend:
    build: .
    container_name: bookstorebackend
    depends_on:
      bookstoredatabase:
        condition: service_healthy
    ports:
      - '8080:8080'
    restart: on-failure