const NotFound = () => {

  return (
    <div className="mx-auto" style={{ maxWidth: "1024px" }} id="applicationPage">
      Page Not Found So Here Is Some Lorem
      <br />
      Lorem ipsum dolor sit amet, consectetur adipiscing elit. Mauris a mollis diam, et pharetra ante. Ut consequat quam a nibh facilisis, et consectetur tortor sollicitudin. Donec ut interdum velit, at faucibus elit. Duis eget vestibulum neque, sed molestie nisl. Fusce luctus accumsan suscipit. Nullam at venenatis diam. Suspendisse tempor fringilla ante, in rhoncus quam tincidunt quis. Vestibulum lacus lorem, maximus eu facilisis sit amet, vehicula ut justo. Duis tortor erat, pulvinar sed ligula vulputate, venenatis convallis massa. Mauris convallis nisl vel facilisis fringilla. Vivamus nisi tortor, aliquet et justo id, placerat pellentesque nulla. Suspendisse ac auctor nisl. Integer gravida fermentum maximus.

      In nec justo fringilla, luctus urna ac, blandit arcu. Quisque commodo efficitur feugiat. Fusce venenatis mi et porttitor pulvinar. Etiam quis pellentesque nibh, vitae interdum felis. Aliquam luctus, felis at consectetur congue, erat diam pellentesque arcu, id luctus lorem orci et felis. Maecenas pellentesque lorem eu leo mollis, id pellentesque eros semper. Sed iaculis tincidunt magna, at rutrum ligula tempor eu. Etiam dictum mollis orci non mollis.

      Vivamus cursus nisl accumsan, viverra sem cursus, molestie tortor. Aliquam porta, massa ac finibus egestas, lorem lacus dapibus tellus, dignissim auctor sapien est euismod eros. Nullam a fermentum eros. Nullam sodales blandit nisl, ut faucibus diam faucibus ut. Nam quis nunc id nisi viverra ullamcorper at finibus metus. Phasellus hendrerit ipsum nec nibh porttitor, a dictum elit placerat. Duis egestas velit eros, vitae placerat neque dapibus et. Donec porttitor pharetra risus, id faucibus lectus maximus id. Suspendisse imperdiet diam id ex blandit, at volutpat nulla tincidunt. Duis eget purus sodales nulla tempor accumsan. Proin scelerisque imperdiet mi vel ultricies. Suspendisse pretium, magna in consequat accumsan, sapien risus ornare dui, volutpat faucibus ante eros ut urna. Nam nec mauris et massa posuere suscipit.

      Sed nec dolor lorem. Nam at eleifend risus, eget maximus urna. Nullam quis arcu vel augue aliquam ultrices. Phasellus vitae auctor orci. Nam facilisis, tortor at aliquet blandit, quam metus accumsan metus, vel fermentum ante enim ut mi. Duis et congue sem. Donec imperdiet lectus at nisl ultricies interdum. Sed scelerisque velit sed accumsan pretium. Aliquam congue volutpat risus, nec molestie odio commodo nec. Nullam vehicula tempus enim id consectetur. Nam lobortis quam vel lectus finibus, non maximus neque efficitur. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Donec a nisl fringilla, finibus diam ut, elementum metus.

      Vivamus luctus aliquet lacus, vel hendrerit diam. Mauris non velit dignissim ante vehicula mattis sit amet non velit. Nam venenatis, mauris vitae sagittis rhoncus, sem risus tincidunt dui, non venenatis neque purus quis est. Nullam in tristique lorem, eu sodales est. Ut accumsan magna mauris, in volutpat sapien feugiat sit amet. Curabitur scelerisque a erat et lacinia. Proin eget aliquam tellus, eu convallis mi. Sed eu elit ex. Curabitur pulvinar massa eu dapibus maximus. Sed nisi nisl, hendrerit quis commodo sed, tempor eget odio. Ut vestibulum ipsum eget pretium bibendum. Cras et laoreet metus. Curabitur semper mi a ipsum eleifend sollicitudin. Pellentesque et metus feugiat, feugiat arcu eget, varius diam.

      Mauris et imperdiet lacus. Fusce sit amet tempor odio. Suspendisse potenti. Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. In feugiat nisi in nisi dignissim sagittis. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nam feugiat metus eget sem euismod maximus at sed justo. Duis non interdum odio, at facilisis ligula. Donec id turpis sit amet nisi egestas pulvinar id nec libero. Mauris aliquam dictum mi, a dignissim risus convallis et. Pellentesque dignissim tellus eget mollis lobortis. Sed rhoncus purus dui, eu tristique quam aliquam eu. Duis varius ullamcorper orci vitae sollicitudin.

      Ut eget nibh ullamcorper leo congue tincidunt. Maecenas quis nunc ac purus sollicitudin dapibus eget sed dolor. Aliquam vestibulum tincidunt nisi ac vehicula. Vestibulum ultrices ligula et tellus facilisis blandit. Fusce varius odio sit amet elit tincidunt, et vehicula felis pharetra. Donec sed leo sed elit tristique euismod non vitae eros. Vivamus enim risus, rhoncus non mauris a, imperdiet maximus nisi. Mauris eget facilisis nisl. Donec eleifend quam commodo, rhoncus mi vel, molestie odio. Vivamus tortor sem, aliquam at erat at, lobortis iaculis erat. Vivamus sit amet justo ultrices, ultrices augue sodales, blandit tellus. Aenean eu tincidunt tortor, euismod venenatis ante. Morbi lacinia venenatis sapien et bibendum.

      Mauris nisi nisl, efficitur ut facilisis at, vulputate vitae dui. Vivamus nulla nibh, tristique et rutrum vitae, volutpat in sem. Aenean sed lectus elit. Integer vestibulum consectetur erat iaculis hendrerit. Aenean venenatis dui ac eros consectetur placerat. Vestibulum finibus enim mauris, at dapibus nisl lobortis a. Pellentesque elit nibh, consectetur non neque ut, efficitur mattis tellus. Nam eu viverra nulla. Vestibulum lacinia vulputate est, non sodales metus mattis eget. Duis rutrum sagittis mollis.

      Maecenas tincidunt ac sem nec tempor. Morbi in massa tincidunt, sollicitudin justo ac, vulputate enim. Phasellus felis dui, rhoncus eu maximus quis, dignissim in diam. Nunc pellentesque, est ac tempus ultrices, justo quam lacinia quam, at ultrices erat lectus eget erat. Nunc in convallis nisl. Nam quis rutrum lectus. Duis eu magna augue. Donec venenatis, ipsum non pretium molestie, tellus turpis viverra lorem, at suscipit leo purus in nunc. Aenean non lacus purus.

      Cras commodo rutrum varius. Donec quis ante metus. Sed tempus libero libero. Duis pulvinar enim nulla, a varius lectus malesuada sit amet. Nulla facilisi. Nulla accumsan velit a malesuada mattis. Praesent porta erat nibh, ac vestibulum diam varius quis.

      Vivamus ullamcorper tristique porta. Donec sed odio arcu. Sed pellentesque, odio commodo laoreet accumsan, metus odio ultrices magna, ac malesuada magna risus vitae ante. In hac habitasse platea dictumst. Ut quis enim placerat, tempus mi quis, aliquam massa. Mauris non risus ut risus bibendum mattis. Lorem ipsum dolor sit amet, consectetur adipiscing elit.

      Nulla ac nunc odio. Pellentesque nulla ligula, auctor id bibendum eget, lobortis vitae magna. Curabitur non enim magna. Proin eget mi elit. Pellentesque vehicula, tortor quis scelerisque aliquet, sapien nunc lobortis justo, at efficitur nunc enim vitae est. Pellentesque cursus est in nibh blandit efficitur. Suspendisse sit amet purus at arcu sagittis rhoncus. Curabitur vitae mauris laoreet, rhoncus neque ac, pellentesque erat. Ut hendrerit luctus turpis ac placerat. Praesent arcu augue, blandit id neque ut, fermentum gravida dui.

      Nunc venenatis scelerisque massa, sed fermentum elit scelerisque vitae. Suspendisse elementum mauris sed ante pulvinar, ac convallis nisl commodo. Vestibulum ultricies ac dui id commodo. Nulla egestas magna quis mi suscipit dictum. Proin varius, nunc vitae rhoncus euismod, massa lectus placerat lacus, in vulputate massa leo eu libero. Mauris tempus fermentum nunc ac viverra. Phasellus eget velit neque. Phasellus molestie nibh sit amet fermentum interdum.

      Nunc sollicitudin facilisis lacus quis molestie. Etiam dignissim aliquam auctor. Cras hendrerit eros sit amet tortor viverra finibus. Curabitur vitae odio neque. Donec porta metus sit amet ante bibendum luctus. Sed libero est, dignissim sit amet nibh eu, condimentum suscipit felis. Nulla vel mauris sed elit ullamcorper porttitor sed vel odio. Proin eleifend vel est ac facilisis. Praesent ullamcorper nisi eros, quis fringilla dui consectetur eu. Aliquam congue dui fringilla, rhoncus sapien id, semper enim. Maecenas justo est, semper non hendrerit sed, porta in lectus. Integer vitae ornare arcu, quis maximus nibh. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Aenean non tortor leo. Sed porta elit vel fringilla vestibulum. Fusce imperdiet dapibus neque eget mattis.
      Mauris ullamcorper venenatis urna. Vivamus ullamcorper in libero vel posuere. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Fusce laoreet, sem sed maximus porttitor, diam enim pharetra erat, ac pretium nulla elit ut nulla. Morbi feugiat pellentesque diam vitae hendrerit. Praesent et turpis maximus, tristique massa et, dapibus risus. Morbi efficitur dictum suscipit. Praesent condimentum tortor id tincidunt posuere. Sed porttitor elementum justo, at ultrices augue pretium et. Curabitur suscipit finibus neque, non vestibulum nisi scelerisque ut. Integer bibendum lacinia tellus, vitae tincidunt dui varius sed.

      Nunc non imperdiet turpis. Nunc vitae ullamcorper ante. Aliquam luctus porta dapibus. Suspendisse potenti. Vivamus nec faucibus ligula. Morbi vel urna non orci ultrices tincidunt id in tellus. Donec sagittis diam sapien, et semper erat porta ullamcorper. Mauris id neque fermentum, porta odio eu, rutrum lacus. Suspendisse ullamcorper blandit pulvinar. Proin sed odio augue. Proin nec sollicitudin nulla, id convallis velit. Duis vitae condimentum augue. Phasellus id ipsum viverra, lacinia lectus nec, facilisis tortor. Cras auctor ut purus sed fermentum. Vivamus augue arcu, porttitor ut aliquet lacinia, ultrices dictum nisi.

      Etiam sit amet velit vitae nisl tristique ultrices. Ut tristique tempus justo, sit amet posuere turpis finibus vitae. Vivamus quis nibh nec felis auctor elementum nec malesuada massa. Duis dictum purus quis lacinia rhoncus. Nunc facilisis risus vitae commodo viverra. Sed tellus tortor, pharetra ac consequat in, mollis non mi. Vestibulum vitae velit at neque tristique aliquet at vel purus. Donec in ipsum accumsan, rutrum nulla eget, rutrum ligula. Nam nunc turpis, elementum eu egestas laoreet, eleifend sed ligula. In dignissim ultrices nulla eu venenatis. Fusce congue auctor sem at rhoncus. Nam feugiat, justo in congue viverra, odio purus pretium nibh, eu dapibus dolor felis vel purus. Duis lobortis dignissim consectetur. Aliquam vel magna sagittis, ultrices erat eget, sollicitudin sapien.

      Proin vitae tellus in dolor dignissim pellentesque. Duis sit amet magna et ante scelerisque scelerisque. Phasellus eget sapien tempor, suscipit libero non, dapibus dolor. Nulla et ligula ante. Aliquam quis maximus erat. Suspendisse auctor dui eu nisi iaculis, quis mollis nulla efficitur. Curabitur finibus dictum nunc, nec placerat quam malesuada at. Etiam imperdiet leo risus, sed varius nulla semper placerat. Donec sapien mi, aliquam id purus porttitor, feugiat ornare lectus. Nunc vitae neque mattis, pretium lectus ut, tincidunt velit. Interdum et malesuada fames ac ante ipsum primis in faucibus.

      Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Aenean vehicula felis eget interdum gravida. Proin a imperdiet nibh, nec vulputate urna. In hac habitasse platea dictumst. Nam semper neque eros, in semper sem feugiat eget. Maecenas gravida facilisis dui, et accumsan diam finibus ac. Mauris ut ex porta, rutrum turpis pellentesque, porta massa. Sed vulputate ipsum eget magna cursus, eget consequat nunc tincidunt. Nam lacinia scelerisque ante non luctus. Vestibulum scelerisque pharetra arcu, nec ultricies magna egestas sed. Donec elementum nibh nec justo accumsan, nec bibendum sapien consectetur. Cras venenatis, ante eget varius feugiat, neque risus accumsan felis, sit amet molestie nulla elit at sapien. Maecenas dui velit, imperdiet sed nisi quis, pharetra semper lorem.

      Vestibulum egestas ac diam sit amet hendrerit. Morbi varius ac mauris vel accumsan. Etiam a nunc fermentum tellus consectetur consectetur. Cras sed lacinia felis, a sollicitudin quam. Etiam mattis ante at tortor suscipit, ut facilisis tellus tempor. Quisque laoreet sem mi, in finibus ipsum commodo ac. Vivamus aliquet odio vel finibus fermentum. Praesent finibus tortor nec fringilla consequat. Quisque tristique ipsum sed odio mollis, vel ultricies nisl vehicula. Nam vel dictum nunc. Proin tristique, tortor vel commodo iaculis, augue ipsum bibendum diam, non suscipit dui est sed turpis. Praesent a felis nunc. Ut eleifend lectus sit amet rutrum pharetra.

      Vivamus vel congue metus. Nulla leo eros, facilisis ac pharetra ut, mattis facilisis sem. Vestibulum auctor velit ac mattis rutrum. Nunc sodales sapien sapien, vel dapibus ligula tincidunt eget. Phasellus vitae ante lectus. Sed sed malesuada dolor. Integer ac purus vel eros commodo eleifend ut iaculis mauris. In non orci sed est bibendum sodales in posuere justo.

      Suspendisse efficitur ornare nunc et elementum. Praesent nisi augue, tincidunt non faucibus in, feugiat et metus. Etiam auctor leo vitae mauris gravida, vel faucibus dui finibus. Nunc ornare, lacus non dapibus euismod, augue nulla fringilla eros, eu lobortis nunc risus in turpis. Mauris faucibus magna nisi, sit amet volutpat ex blandit scelerisque. Vestibulum at tortor urna. Suspendisse nec purus vulputate, auctor libero sed, faucibus magna. Morbi tincidunt fringilla odio, maximus tempus augue egestas vel. Cras vehicula urna id diam pulvinar, at pretium neque convallis. Nulla magna felis, consequat eu pellentesque maximus, sagittis non purus.

      Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. In congue est nibh, ac dapibus ante facilisis eget. Donec laoreet ligula sit amet nunc elementum, vel accumsan purus gravida. Vivamus mollis, sem quis dapibus laoreet, tellus velit pulvinar nulla, ac finibus justo lectus ut massa. Vivamus in mauris auctor, malesuada nisl id, efficitur mauris. In vestibulum sollicitudin magna eget gravida. Suspendisse vitae metus sit amet leo tempor aliquam sed et diam. Nunc elit purus, ornare at purus in, elementum dapibus nulla. Quisque auctor ac urna ut viverra. Pellentesque quis mauris maximus, efficitur libero a, sollicitudin nulla. Ut porta fermentum nunc id eleifend.
    </div>
  )

}

export default NotFound